server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://m-code-user
          predicates:
            - Path=/api/user/**
        - id: question-service
          uri: lb://m-code-question
          predicates:
            - Path=/api/question/**
        - id: judge-service
          uri: lb://m-code-judge
          predicates:
            - Path=/api/judge/**
        - id: exam-service
          uri: lb://m-code-exam
          predicates:
            - Path=/api/exam/**
        - id: knowledge-service
          uri: lb://m-code-knowledge
          predicates:
            - Path=/api/knowledge/**
        - id: ai-service
          uri: lb://m-code-ai
          predicates:
            - Path=/api/ai/**

logging:
  level:
    com.mcode: debug
